### ISSUE TITLE
pe 3.3.0 not compatible with version 0.9.2

### ISSUE THREAD

**Issue by ltutar** [counsyl/puppet-windows#1]
When I try to install the module, I get the following error:
Error: Could not install module 'counsyl-windows' (???)
  No version of 'counsyl-windows' can satisfy all dependencies
    Use `puppet module install --ignore-dependencies` to install only this module

thank you,

Levent

**Comment by jonemo** [comment]
I think this issue is stale and wasn't caused by this module originally. Reopen if you disagree :)

**Comment by ltutar** [comment]
ok. just for the record. I do not have the issue with PE2016.1.1.
```
[root@puppetmaster manifests]# puppet module install counsyl-windows
Notice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...
Notice: Downloading from https://forgeapi.puppetlabs.com ...
Notice: Installing -- do not interrupt ...
/etc/puppetlabs/code/environments/production/modules
└─┬ counsyl-windows (v1.0.3)
  ├─┬ counsyl-sys (v0.9.19)
  │ └── puppetlabs-stdlib (v4.11.0)
  ├── puppetlabs-powershell (v1.0.6)
  └── puppetlabs-registry (v1.1.3)
[root@puppetmaster manifests]# puppet --version
4.4.1
[root@puppetmaster manifests]# 
```
