### ISSUE TITLE
Regex for update time is wrong

### ISSUE THREAD

**Issue by makomatic** [counsyl/puppet-windows#16]
code/modules/windows/manifests/update.pp 
 View file @ 58717d1a
...	...
```
@@ -84,7 +84,7 @@ class windows::update(
  validate_bool($all_users)
  validate_re($type, '^[2-5]$')
  validate_re($day, '^[0-7]$')
-  validate_re($time, '^[0-23]$')
+  validate_re($time, '^(\d|1\d|2[0-4])(\.\d{1,2})?$')
  validate_bool($reboot_required)
```

The regex is not working like that - [] is for single characters (...ranges).

**Comment by jdavisp3** [comment]
Doh, good call. I guess the `(\.\d{1,2})?` is for optional fractional seconds?

**Comment by makomatic** [comment]
Yeah, ^(\d|1\d|2[0-4])$ is absolutely sufficient for 0-24
