### ISSUE TITLE
windows::update idempotence issue on Windows 8/2k12

### ISSUE THREAD

**Issue by rogerlz** [counsyl/puppet-windows#17]
Windows 8 and 2012 have changed the way that the windows update service works, and a new feature called Trigger Start makes the service to be stopped for inactivity. 

The issue is that the windows::update class is always trying to start the service.

Reference: https://tickets.puppetlabs.com/browse/MODULES-2420

**Comment by jonemo** [comment]
Fixed in #18, thanks @rogerlz!
