### ISSUE TITLE
Windows Shortcuts for URLs

### ISSUE THREAD

**Issue by krulls** [counsyl/puppet-windows#7]
The class [windows::shortcut](https://github.com/counsyl/puppet-windows/blob/master/manifests/shortcut.pp) is not usable for all kind of URLs because function [validate_absolute_path](https://github.com/puppetlabs/puppetlabs-stdlib/blob/master/lib/puppet/parser/functions/validate_absolute_path.rb) fails when _target_ is a web link (i. e. "http://www.google.de") or a network share (i. e. "\\my\shared\folder") or a mail link (i. e. "mailto://gunter.goesto@dada.com").

To honor the common possibility in Windows to create shortcuts with more kinds of URLs than just file links I plead to skip the absolute path validation of the _target_ parameter.

**Comment by jonemo** [comment]
Addressed in #8
